# Generated by Django 5.1.4 on 2025-01-15 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('PAID', 'Paid'), ('CANCELED', 'Canceled')], default='WAITING', max_length=20, verbose_name='status')),
                ('table_number', models.PositiveIntegerField(unique=True, verbose_name='table number')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='total price')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='cashier')),
            ],
            options={
                'unique_together': {('status', 'table_number')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('PREPARED', 'Prepared'), ('CANCELED', 'Canceled')], default='WAITING', max_length=20, verbose_name='status')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='image')),
                ('product_name', models.CharField(max_length=255, verbose_name='product name')),
                ('product_quantity', models.PositiveSmallIntegerField(default=1)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='total price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_orders.ordermodel', verbose_name='order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
