# Generated by Django 5.1.4 on 2025-01-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('ORDINARY', 'Ordinary'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier')], default='ORDINARY', max_length=20),
        ),
    ]
